### ISSUE TITLE
./bin/sparqlify, Cannot process web requests due to missing Java message body writer

### ISSUE THREAD

**Issue by julian1** [SmartDataAnalytics/Sparqlify#54]
Postgresql database created and populated according to simplified Wortschatz example, 

Start jetty,
/Sparqlify/sparqlify-core$ ./bin/sparqlify -h localhost -u meteo -p meteo -d meteo  -m ./Wortschatz.sparqlify  -n 1000 -t 30 2>&1 | tee out.log

Navigate to,
http://localhost:7531/sparql

$ cat out.log

2014-09-11 08:57:53,486 DEBUG org.apache.jena.riot.stream.JenaIOEnvironment: Failed to find configuration: location-mapping.ttl;location-mapping.rdf;location-mapping.n3;etc/location-mapping.rdf;etc/location-mapping.n3;etc/location-mapping.ttl
2014-09-11 08:57:53,687 WARN  org.aksw.sparqlify.core.cast.TypeSystemImpl: Skipping: integer, integer
2014-09-11 08:57:53,688 WARN  org.aksw.sparqlify.core.cast.TypeSystemImpl: Skipping: float, float
2014-09-11 08:57:53,688 WARN  org.aksw.sparqlify.core.cast.TypeSystemImpl: Skipping: geometry, geometry
2014-09-11 08:57:53,688 WARN  org.aksw.sparqlify.core.cast.TypeSystemImpl: Skipping: timestamp, timestamp
2014-09-11 08:57:53,688 WARN  org.aksw.sparqlify.core.cast.TypeSystemImpl: Skipping: geography, geography
2014-09-11 08:57:54,022 INFO  org.aksw.sparqlify.web.HttpSparqlEndpoint: Errors: 0, Warnings: 0
2014-09-11 08:57:54,030 WARN  org.aksw.sparqlify.core.cast.TypeSystemImpl: Skipping: integer, integer
2014-09-11 08:57:54,030 WARN  org.aksw.sparqlify.core.cast.TypeSystemImpl: Skipping: float, float
2014-09-11 08:57:54,030 WARN  org.aksw.sparqlify.core.cast.TypeSystemImpl: Skipping: geometry, geometry
2014-09-11 08:57:54,031 WARN  org.aksw.sparqlify.core.cast.TypeSystemImpl: Skipping: timestamp, timestamp
2014-09-11 08:57:54,031 WARN  org.aksw.sparqlify.core.cast.TypeSystemImpl: Skipping: geography, geography
2014-09-11 08:57:54,657 DEBUG org.eclipse.jetty.util.log: Logging to org.slf4j.impl.Log4jLoggerAdapter(org.eclipse.jetty.util.log) via org.eclipse.jetty.util.log.Slf4jLog
2014-09-11 08:57:54,671 DEBUG org.eclipse.jetty.util.component.Container: Container org.eclipse.jetty.server.Server@38d8381b + SelectChannelConnector@0.0.0.0:7531 as connector
2014-09-11 08:57:54,680 DEBUG org.eclipse.jetty.util.component.Container: Container org.eclipse.jetty.server.Server@38d8381b + o.e.j.s.ServletContextHandler{/,null} as handler
2014-09-11 08:57:54,686 DEBUG org.eclipse.jetty.servlet.ServletHandler: filterNameMap={}
2014-09-11 08:57:54,686 DEBUG org.eclipse.jetty.servlet.ServletHandler: pathFilters=null
2014-09-11 08:57:54,686 DEBUG org.eclipse.jetty.servlet.ServletHandler: servletFilterMap=null
2014-09-11 08:57:54,686 DEBUG org.eclipse.jetty.servlet.ServletHandler: servletPathMap={/_=com.sun.jersey.spi.container.servlet.ServletContainer-261687761}
2014-09-11 08:57:54,686 DEBUG org.eclipse.jetty.servlet.ServletHandler: servletNameMap={com.sun.jersey.spi.container.servlet.ServletContainer-261687761=com.sun.jersey.spi.container.servlet.ServletContainer-261687761}
2014-09-11 08:57:54,686 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: starting org.eclipse.jetty.server.Server@38d8381b
2014-09-11 08:57:54,687 INFO  org.eclipse.jetty.server.Server: jetty-8.y.z-SNAPSHOT
2014-09-11 08:57:54,698 DEBUG org.eclipse.jetty.util.component.Container: Container org.eclipse.jetty.server.Server@38d8381b + qtp1997915906{8<=0<=0/254,-1} as threadpool
2014-09-11 08:57:54,698 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: starting o.e.j.s.ServletContextHandler{/,null}
2014-09-11 08:57:54,715 DEBUG org.eclipse.jetty.util.component.Container: Container org.eclipse.jetty.servlet.ServletHandler@3847efa5 + com.sun.jersey.spi.container.servlet.ServletContainer-261687761 as servlet
2014-09-11 08:57:54,716 DEBUG org.eclipse.jetty.util.component.Container: Container org.eclipse.jetty.servlet.ServletHandler@3847efa5 + [/_]=>com.sun.jersey.spi.container.servlet.ServletContainer-261687761 as servletMapping
2014-09-11 08:57:54,716 DEBUG org.eclipse.jetty.util.component.Container: Container org.eclipse.jetty.server.session.SessionHandler@7ac65680 + org.eclipse.jetty.servlet.ServletHandler@3847efa5 as handler
2014-09-11 08:57:54,716 DEBUG org.eclipse.jetty.util.component.Container: Container org.eclipse.jetty.server.session.SessionHandler@7ac65680 + org.eclipse.jetty.server.session.HashSessionManager@73592c78 as sessionManager
2014-09-11 08:57:54,716 DEBUG org.eclipse.jetty.util.component.Container: Container o.e.j.s.ServletContextHandler{/,null} + org.eclipse.jetty.server.session.SessionHandler@7ac65680 as handler
2014-09-11 08:57:54,716 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: starting org.eclipse.jetty.server.session.SessionHandler@7ac65680
2014-09-11 08:57:54,716 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: starting org.eclipse.jetty.server.session.HashSessionManager@73592c78
2014-09-11 08:57:54,717 DEBUG org.eclipse.jetty.util.component.Container: Container org.eclipse.jetty.server.Server@38d8381b + org.eclipse.jetty.server.session.HashSessionIdManager@34ba9d81 as sessionIdManager
2014-09-11 08:57:54,717 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: starting org.eclipse.jetty.server.session.HashSessionIdManager@34ba9d81
2014-09-11 08:57:54,717 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: STARTED org.eclipse.jetty.server.session.HashSessionIdManager@34ba9d81
2014-09-11 08:57:54,717 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: STARTED org.eclipse.jetty.server.session.HashSessionManager@73592c78
2014-09-11 08:57:54,717 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: starting org.eclipse.jetty.servlet.ServletHandler@3847efa5
2014-09-11 08:57:54,718 DEBUG org.eclipse.jetty.servlet.ServletHandler: filterNameMap={}
2014-09-11 08:57:54,718 DEBUG org.eclipse.jetty.servlet.ServletHandler: pathFilters=null
2014-09-11 08:57:54,718 DEBUG org.eclipse.jetty.servlet.ServletHandler: servletFilterMap=null
2014-09-11 08:57:54,718 DEBUG org.eclipse.jetty.servlet.ServletHandler: servletPathMap={/_=com.sun.jersey.spi.container.servlet.ServletContainer-261687761}
2014-09-11 08:57:54,718 DEBUG org.eclipse.jetty.servlet.ServletHandler: servletNameMap={com.sun.jersey.spi.container.servlet.ServletContainer-261687761=com.sun.jersey.spi.container.servlet.ServletContainer-261687761}
2014-09-11 08:57:54,718 DEBUG org.eclipse.jetty.server.handler.AbstractHandler: starting org.eclipse.jetty.servlet.ServletHandler@3847efa5
2014-09-11 08:57:54,718 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: STARTED org.eclipse.jetty.servlet.ServletHandler@3847efa5
2014-09-11 08:57:54,718 DEBUG org.eclipse.jetty.server.handler.AbstractHandler: starting org.eclipse.jetty.server.session.SessionHandler@7ac65680
2014-09-11 08:57:54,718 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: STARTED org.eclipse.jetty.server.session.SessionHandler@7ac65680
2014-09-11 08:57:54,718 DEBUG org.eclipse.jetty.server.handler.AbstractHandler: starting o.e.j.s.ServletContextHandler{/,null}
2014-09-11 08:57:54,718 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: starting com.sun.jersey.spi.container.servlet.ServletContainer-261687761
2014-09-11 08:57:54,719 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: STARTED com.sun.jersey.spi.container.servlet.ServletContainer-261687761
2014-09-11 08:57:54,719 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: STARTED o.e.j.s.ServletContextHandler{/,null}
2014-09-11 08:57:54,719 DEBUG org.eclipse.jetty.server.handler.AbstractHandler: starting org.eclipse.jetty.server.Server@38d8381b
2014-09-11 08:57:54,719 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: starting qtp1997915906{8<=0<=0/254,-1}
2014-09-11 08:57:54,720 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: STARTED qtp1997915906{8<=7<=8/254,0}
2014-09-11 08:57:54,720 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: starting SelectChannelConnector@0.0.0.0:7531
2014-09-11 08:57:54,722 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: starting null/null
2014-09-11 08:57:54,724 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: STARTED PooledBuffers [0/1024@6144,0/1024@16384,0/1024@-]/PooledBuffers [0/1024@6144,0/1024@32768,0/1024@-]
2014-09-11 08:57:54,724 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: starting org.eclipse.jetty.server.nio.SelectChannelConnector$ConnectorSelectorManager@b5d456b
2014-09-11 08:57:54,727 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: STARTED org.eclipse.jetty.server.nio.SelectChannelConnector$ConnectorSelectorManager@b5d456b
2014-09-11 08:57:54,727 DEBUG org.eclipse.jetty.io.nio: Starting Thread[qtp1997915906-17 Selector0,5,main] on org.eclipse.jetty.io.nio.SelectorManager$1@348dc1ef
2014-09-11 08:57:54,728 INFO  org.eclipse.jetty.server.AbstractConnector: Started SelectChannelConnector@0.0.0.0:7531
2014-09-11 08:57:54,728 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: STARTED SelectChannelConnector@0.0.0.0:7531
2014-09-11 08:57:54,728 DEBUG org.eclipse.jetty.util.component.AbstractLifeCycle: STARTED org.eclipse.jetty.server.Server@38d8381b
2014-09-11 08:58:03,987 DEBUG org.eclipse.jetty.io.nio: created SCEP@49740540{l(/0:0:0:0:0:0:0:1:55575)<->r(/0:0:0:0:0:0:0:1:7531),s=0,open=true,ishut=false,oshut=false,rb=false,wb=false,w=true,i=0}-{AsyncHttpConnection@6004d26c,g=HttpGenerator{s=0,h=-1,b=-1,c=-1},p=HttpParser{s=-14,l=0,c=0},r=0}
2014-09-11 08:58:03,988 DEBUG org.eclipse.jetty.http.HttpParser: filled 1130/1130
2014-09-11 08:58:03,993 DEBUG org.eclipse.jetty.server.Server: REQUEST /sparql on AsyncHttpConnection@6004d26c,g=HttpGenerator{s=0,h=-1,b=-1,c=-1},p=HttpParser{s=-5,l=10,c=0},r=1
2014-09-11 08:58:03,993 DEBUG org.eclipse.jetty.server.handler.ContextHandler: scope null||/sparql @ o.e.j.s.ServletContextHandler{/,null}
2014-09-11 08:58:03,993 DEBUG org.eclipse.jetty.server.handler.ContextHandler: context=||/sparql @ o.e.j.s.ServletContextHandler{/,null}
2014-09-11 08:58:03,995 DEBUG org.eclipse.jetty.server.session: sessionManager=org.eclipse.jetty.server.session.HashSessionManager@73592c78
2014-09-11 08:58:03,996 DEBUG org.eclipse.jetty.server.session: session=null
2014-09-11 08:58:03,996 DEBUG org.eclipse.jetty.servlet.ServletHandler: servlet ||/sparql -> com.sun.jersey.spi.container.servlet.ServletContainer-261687761
2014-09-11 08:58:03,996 DEBUG org.eclipse.jetty.servlet.ServletHandler: chain=null
Sep 11, 2014 8:58:04 AM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  org.aksw.sparqlify.web
Sep 11, 2014 8:58:04 AM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class org.aksw.sparqlify.web.HttpSparqlEndpoint
Sep 11, 2014 8:58:04 AM com.sun.jersey.api.core.ScanningResourceConfig init
INFO: No provider classes found.
Sep 11, 2014 8:58:04 AM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.17 01/17/2013 03:31 PM'
Sep 11, 2014 8:58:04 AM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Adding the following classes declared in META-INF/services/jersey-server-components to the resource configuration:
  class org.atmosphere.jersey.AtmosphereResourceConfigurator
Sep 11, 2014 8:58:05 AM com.sun.jersey.spi.container.ContainerResponse write
SEVERE: A message body writer for Java class org.aksw.sparqlify.web.StreamingOutputString, and Java type interface javax.ws.rs.core.StreamingOutput, and MIME media type application/xml was not found
Sep 11, 2014 8:58:05 AM com.sun.jersey.spi.container.ContainerResponse write
SEVERE: The registered message body writers compatible with the MIME media type are:
*/_ ->
  com.sun.jersey.server.impl.template.ViewableMessageBodyWriter

Sep 11, 2014 8:58:05 AM com.sun.jersey.spi.container.ContainerResponse logException
SEVERE: Mapped exception to response: 500 (Internal Server Error)
javax.ws.rs.WebApplicationException: com.sun.jersey.api.MessageException: A message body writer for Java class org.aksw.sparqlify.web.StreamingOutputString, and Java type interface javax.ws.rs.core.StreamingOutput, and MIME media type application/xml was not found
    at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:285)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1479)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:366)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:722)
Caused by: com.sun.jersey.api.MessageException: A message body writer for Java class org.aksw.sparqlify.web.StreamingOutputString, and Java type interface javax.ws.rs.core.StreamingOutput, and MIME media type application/xml was not found
    ... 29 more

2014-09-11 08:58:05,403 DEBUG org.eclipse.jetty.server.Server: RESPONSE /sparql  500 handled=true
2014-09-11 08:58:05,404 DEBUG org.eclipse.jetty.server.AsyncHttpConnection: Enabled read interest SCEP@49740540{l(/0:0:0:0:0:0:0:1:55575)<->r(/0:0:0:0:0:0:0:1:7531),s=1,open=true,ishut=false,oshut=false,rb=false,wb=false,w=true,i=0r}-{AsyncHttpConnection@6004d26c,g=HttpGenerator{s=4,h=0,b=0,c=-1},p=HttpParser{s=0,l=10,c=0},r=1}
2014-09-11 08:58:05,406 DEBUG org.eclipse.jetty.http.HttpParser: filled 0/0

**Comment by Aklakan** [comment]
Most likely this issue is no longer relevant to the current sparql server.
